/**
 * Tests for the monthly auto-generation orchestrator's email-guard behaviour.
 *
 * Key invariant: when every product's schedule for next month already exists,
 * generateSchedule returns { skipped: true } for each product, generatedProducts
 * stays empty, and sendNotification must NEVER be called.
 *
 * These tests run against the pure lib function (runMonthlyAutoGenerate) which
 * has no workspace-package imports, so no bundler or module mocking is needed.
 *
 * Run with: pnpm --filter @workspace/api-server test
 */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import {
  runMonthlyAutoGenerate,
  type AutoGenerateDeps,
} from "./runMonthlyAutoGenerate.ts";

// ─── Shared test fixtures ─────────────────────────────────────────────────────

const MONTH_KEY = "2099-09"; // far future — never clashes with real data
const NEXT_M    = new Date(2099, 8, 1); // September 2099

const MOCK_PRODUCTS = [
  { id: 1, name: "Product A" },
  { id: 2, name: "Product B" },
  { id: 3, name: "Product C" },
];

const MOCK_OWNERS = [
  { email: "alice@example.com", name: "Alice" },
  { email: "bob@example.com",   name: "Bob"   },
];

/** stub: every product already has posts → skip */
const allSkipped: AutoGenerateDeps["generateSchedule"] = async () => ({
  skipped: true,
  count: 0,
});

/** stub: every product is freshly generated */
const allGenerated: AutoGenerateDeps["generateSchedule"] = async () => ({
  skipped: false,
  count: 60,
});

/** Minimal no-op logger */
const noopLog: AutoGenerateDeps["log"] = {
  info:  () => {},
  error: () => {},
};

/** Helper: build a deps object with sensible defaults, overrideable per-test */
function makeDeps(overrides: Partial<AutoGenerateDeps>): AutoGenerateDeps {
  return {
    fetchProducts:    async () => MOCK_PRODUCTS,
    generateSchedule: allSkipped,
    fetchOwners:      async () => MOCK_OWNERS,
    sendNotification: async () => null,
    buildEmail:       () => "<html>stub</html>",
    getBaseUrl:       () => "https://app.example.com",
    log:              noopLog,
    ...overrides,
  };
}

// ─── Suite 1: all schedules already exist ─────────────────────────────────────

describe("runMonthlyAutoGenerate – all products already have schedules", () => {
  it("returns generated=0, skipped=N, failed=0", async () => {
    const result = await runMonthlyAutoGenerate(makeDeps({}), MONTH_KEY, NEXT_M);

    assert.equal(result.generated, 0,                   "generated should be 0");
    assert.equal(result.skipped,   MOCK_PRODUCTS.length, `skipped should equal the number of products (${MOCK_PRODUCTS.length})`);
    assert.equal(result.failed,    0,                   "failed should be 0");
  });

  it("does not call sendNotification when generatedProducts is empty", async () => {
    let calls = 0;

    await runMonthlyAutoGenerate(
      makeDeps({ sendNotification: async () => { calls++; return null; } }),
      MONTH_KEY,
      NEXT_M,
    );

    assert.equal(calls, 0, `sendNotification must not be called, but was called ${calls} time(s)`);
  });

  it("does not even call fetchOwners when nothing was generated", async () => {
    // fetchOwners is inside the `if (generatedProducts.length > 0)` guard,
    // so it should be short-circuited entirely.
    let ownerFetches = 0;

    await runMonthlyAutoGenerate(
      makeDeps({
        fetchOwners: async () => { ownerFetches++; return MOCK_OWNERS; },
      }),
      MONTH_KEY,
      NEXT_M,
    );

    assert.equal(ownerFetches, 0, "fetchOwners should not be called when no schedules were generated");
  });

  it("handles an empty product list: returns all zeros, no email", async () => {
    let calls = 0;

    const result = await runMonthlyAutoGenerate(
      makeDeps({
        fetchProducts:    async () => [],
        sendNotification: async () => { calls++; return null; },
      }),
      MONTH_KEY,
      NEXT_M,
    );

    assert.equal(result.generated, 0);
    assert.equal(result.skipped,   0);
    assert.equal(result.failed,    0);
    assert.equal(calls, 0, "sendNotification must not be called for an empty product list");
  });
});

// ─── Suite 2: result shape contract ──────────────────────────────────────────

describe("runMonthlyAutoGenerate – result shape", () => {
  it("always returns an object with generated, skipped, and failed numeric keys", async () => {
    const result = await runMonthlyAutoGenerate(makeDeps({}), MONTH_KEY, NEXT_M);

    assert.ok("generated" in result, "result must have a 'generated' key");
    assert.ok("skipped"   in result, "result must have a 'skipped' key");
    assert.ok("failed"    in result, "result must have a 'failed' key");
    assert.equal(typeof result.generated, "number");
    assert.equal(typeof result.skipped,   "number");
    assert.equal(typeof result.failed,    "number");
  });
});

// ─── Suite 3: email IS sent when new schedules are generated ──────────────────

describe("runMonthlyAutoGenerate – email fires when schedules ARE newly generated", () => {
  it("calls sendNotification once per owner when products were freshly generated", async () => {
    const recipients: string[] = [];

    const result = await runMonthlyAutoGenerate(
      makeDeps({
        fetchProducts:    async () => [{ id: 1, name: "Product A" }],
        generateSchedule: allGenerated,
        fetchOwners:      async () => MOCK_OWNERS,
        sendNotification: async (opts) => { recipients.push(opts.to); return "msg-id"; },
      }),
      MONTH_KEY,
      NEXT_M,
    );

    assert.equal(result.generated, 1, "one product should be counted as generated");
    assert.equal(result.skipped,   0);
    assert.equal(result.failed,    0);
    assert.equal(
      recipients.length,
      MOCK_OWNERS.length,
      `sendNotification should be called once per owner (${MOCK_OWNERS.length} times)`,
    );
    assert.deepEqual(
      recipients.sort(),
      MOCK_OWNERS.map((o) => o.email).sort(),
      "each owner should receive exactly one notification",
    );
  });

  it("does NOT call sendNotification when owners list is empty even if schedules were generated", async () => {
    let calls = 0;

    await runMonthlyAutoGenerate(
      makeDeps({
        generateSchedule: allGenerated,
        fetchOwners:      async () => [],
        sendNotification: async () => { calls++; return null; },
      }),
      MONTH_KEY,
      NEXT_M,
    );

    assert.equal(calls, 0, "no email should be sent when there are no owner users");
  });
});

// ─── Suite 4: per-product failure handling ────────────────────────────────────

describe("runMonthlyAutoGenerate – per-product failure handling", () => {
  it("increments failed counter and continues processing remaining products", async () => {
    const products = [
      { id: 1, name: "Good Product"    },
      { id: 2, name: "Broken Product"  },
      { id: 3, name: "Good Product 2"  },
    ];

    const result = await runMonthlyAutoGenerate(
      makeDeps({
        fetchProducts: async () => products,
        generateSchedule: async (id) => {
          if (id === 2) throw new Error("simulated failure");
          return { skipped: true, count: 0 };
        },
      }),
      MONTH_KEY,
      NEXT_M,
    );

    assert.equal(result.failed,    1, "one product should be counted as failed");
    assert.equal(result.skipped,   2, "the other two products should be skipped");
    assert.equal(result.generated, 0);
  });

  it("does not send email when all products failed", async () => {
    let calls = 0;

    const result = await runMonthlyAutoGenerate(
      makeDeps({
        generateSchedule: async () => { throw new Error("always fails"); },
        sendNotification: async () => { calls++; return null; },
      }),
      MONTH_KEY,
      NEXT_M,
    );

    assert.equal(result.failed, MOCK_PRODUCTS.length);
    assert.equal(calls, 0, "sendNotification must not be called when all products failed");
  });
});
