/**
 * Pure orchestration logic for the monthly social-schedule auto-generation cron.
 *
 * This module has no direct database or email imports so it can be exercised in
 * unit tests without a bundler.  All external I/O is injected via `deps`.
 */

export interface GenerateScheduleResult {
  skipped?: boolean;
  count: number;
}

export interface ScheduledProduct {
  id: number;
  name: string;
  count: number;
}

export interface AutoGenerateResult {
  generated: number;
  skipped: number;
  failed: number;
}

export interface AutoGenerateDeps {
  /** Fetch products that should be included in this run. */
  fetchProducts: () => Promise<{ id: number; name: string }[]>;
  /** Generate (or skip) the schedule for a single product. */
  generateSchedule: (
    productId: number,
    monthKey: string,
    opts: { skipIfExists?: boolean },
  ) => Promise<GenerateScheduleResult>;
  /** Fetch owner users who should receive the notification email. */
  fetchOwners: () => Promise<{ email: string; name: string | null }[]>;
  /** Send one notification email; returns a message ID or null. */
  sendNotification: (opts: { to: string; subject: string; html: string }) => Promise<string | null>;
  /** Build the HTML body for the notification email. */
  buildEmail: (products: ScheduledProduct[], monthLabel: string, baseUrl: string) => string;
  /** Return the base app URL used in email links. */
  getBaseUrl: () => string;
  /** Logger with at least info/error methods. */
  log: {
    info: (ctx: Record<string, unknown>, msg: string) => void;
    error: (ctx: Record<string, unknown>, msg: string) => void;
  };
}

/**
 * Core monthly auto-generation orchestrator.
 *
 * @param deps   - Injected I/O dependencies (DB, email, logger, …)
 * @param monthKey - Target month in "YYYY-MM" format
 * @param nextM    - First day of the target month (used only for the email label)
 */
export async function runMonthlyAutoGenerate(
  deps: AutoGenerateDeps,
  monthKey: string,
  nextM: Date,
): Promise<AutoGenerateResult> {
  const { fetchProducts, generateSchedule, fetchOwners, sendNotification, buildEmail, getBaseUrl, log } = deps;

  const products = await fetchProducts();

  let generated = 0, skipped = 0, failed = 0;
  const generatedProducts: ScheduledProduct[] = [];

  for (const product of products) {
    try {
      const result = await generateSchedule(product.id, monthKey, { skipIfExists: true });
      if (result.skipped) {
        skipped++;
      } else if (result.count > 0) {
        generated++;
        generatedProducts.push({ id: product.id, name: product.name, count: result.count });
      }
    } catch (err) {
      log.error({ err: err as object, productId: product.id }, "social: monthly auto-gen failed for product");
      failed++;
    }
  }

  // ── Email guard: only fire when at least one schedule was newly generated ──
  if (generatedProducts.length > 0) {
    try {
      const owners = await fetchOwners();

      if (owners.length > 0) {
        const base = getBaseUrl();
        const monthLabel = nextM.toLocaleDateString("en-US", { month: "long", year: "numeric" });
        const html = buildEmail(generatedProducts, monthLabel, base);
        const subject = `Social schedule ready: ${monthLabel} (${generatedProducts.length} product${generatedProducts.length === 1 ? "" : "s"})`;

        for (const owner of owners) {
          await sendNotification({ to: owner.email, subject, html });
        }
        log.info(
          { owners: owners.length, products: generatedProducts.length },
          "social: schedule notification emails sent",
        );
      }
    } catch (err) {
      // Non-fatal — log but don't fail the generation result
      log.error({ err: err as object }, "social: failed to send schedule notification email");
    }
  }

  return { generated, skipped, failed };
}
