import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import productsRouter from "./products";
import goalsRouter from "./goals";
import platformStatesRouter from "./platformStates";
import resourcesRouter from "./resources";
import activitiesRouter from "./activities";
import reflectionsRouter from "./reflections";
import analysesRouter from "./analyses";
import summaryRouter from "./summary";
import toolAdvisorRouter from "./toolAdvisor";
import visionItemsRouter from "./visionItems";
import webauthnRouter from "./webauthn";
import chatRouter from "./chat";
import storageRouter from "./storage";
import productDocumentsRouter from "./productDocuments";
import salesTargetsRouter from "./salesTargets";
import pipelineRouter from "./pipeline";
import teamRouter from "./team";
import generateGoalsRouter from "./generateGoals";
import leadsRouter from "./leads";
import emailTemplatesRouter from "./emailTemplates";
import emailSendsRouter from "./emailSends";
import linkedinTemplatesRouter from "./linkedinTemplates";
import productAssignmentsRouter from "./productAssignments";
import outreachRouter from "./outreach";
import revenueLinesRouter from "./revenueLines";
import generateTemplateRouter from "./generateTemplate";
import leadImageExtractRouter from "./leadImageExtract";
import emailSequencesRouter from "./emailSequences";
import socialPostsRouter from "./socialPosts";
import socialAuthRouter from "./socialAuth";
import productAssetsRouter from "./productAssets";
import contactListsRouter from "./contactLists";
import unsubscribeRouter from "./unsubscribe";
import userProductEmailSettingsRouter from "./userProductEmailSettings";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(productsRouter);
router.use(goalsRouter);
router.use(platformStatesRouter);
router.use(resourcesRouter);
router.use(activitiesRouter);
router.use(reflectionsRouter);
router.use(analysesRouter);
router.use(summaryRouter);
router.use(toolAdvisorRouter);
router.use(visionItemsRouter);
router.use(webauthnRouter);
router.use(chatRouter);
router.use(storageRouter);
router.use(productDocumentsRouter);
router.use(salesTargetsRouter);
router.use(pipelineRouter);
router.use(teamRouter);
router.use(generateGoalsRouter);
router.use(leadsRouter);
router.use(emailTemplatesRouter);
router.use(emailSendsRouter);
router.use(linkedinTemplatesRouter);
router.use(productAssignmentsRouter);
router.use(outreachRouter);
router.use(revenueLinesRouter);
router.use(generateTemplateRouter);
router.use(leadImageExtractRouter);
router.use(emailSequencesRouter);
router.use(socialPostsRouter);
router.use(socialAuthRouter);
router.use(productAssetsRouter);
router.use(contactListsRouter);
router.use(unsubscribeRouter);
router.use(userProductEmailSettingsRouter);

export default router;
